apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: "Dan's Homelab"
    theme: dark
  services.yaml: "[]"
  widgets.yaml: "[]"
  bookmarks.yaml: "[]"
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
  kubernetes.yaml: ""
