apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-webapp
  template:
    metadata:
      labels:
        app: fastapi-webapp
    spec:
      containers:
      - name: webapp
        image: ghcr.io/danxtrate/homelab-webapp/webapp:f2120eb688dd883529726cdbc7970e9b77bcae9b
        ports:
        - containerPort: 8000
