apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-backup
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/danxtrate/homelab-gitops.git
    targetRevision: main
    path: workloads/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
